## https://pre-commit.com
# pre-commit install -t pre-commit
#
# Run hooks on repo:
# pre-commit run --all-files [hook-id]
#
# Update repos:
# pre-commit autoupdate
---
repos:
  - repo: https://github.com/boidolr/pre-commit-images
    rev: v1.2.0
    hooks:
      - id: optimize-avif
        exclude: ^tests
      - id: optimize-jpg
        exclude: ^tests
      - id: optimize-png
        exclude: ^tests
      - id: optimize-svg
        exclude: ^tests
      - id: optimize-webp
        exclude: ^tests

  - repo: https://github.com/boidolr/pre-commit-text
    rev: v1.1.1
    hooks:
      - id: pretty-format-yaml
        args: [--preserve-quotes]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        files: \.(py|yaml)$
        args: [--fix=lf]
      - id: pretty-format-json
        args: [--autofix, --indent=4, --no-sort-keys]
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: rst-backticks

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args: [--py39-plus]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [--configfile, .bandit.yaml]
